version: "2.4"
services:

  nginx:
    build: ./nginx
    image: chat-frontend
    restart: always
    ports:
      - 443:443
    volumes:
      - /data/chat/certs:/opt/certs
    depends_on:
      - tinode
    networks:
      - chat

  tinode:
    build:
      context: ./bin
      dockerfile: ../Dockerfile
    image: chat-backend
    restart: always
    volumes:
      - /data/chat/config:/etc/chat
    depends_on:
      - rethinkdb
    networks:
      - chat

  rethinkdb:
    image: rethinkdb
    restart: always
    ports:
      - 38412:8080
    volumes:
      - /data/chat/db:/data
    networks:
      - chat

networks:
  chat:
    driver: bridge
