version: "2.4"
services:

  server:
    build:
      context: ./bin
      dockerfile: ../Dockerfile
    image: chat
    restart: always
    ports:
      - 6060:6060
    volumes:
      - /data/chat/config:/etc/chat
    depends_on:
      - rethinkdb
    networks:
      - chat

  rethinkdb:
    image: rethinkdb
    restart: always
    ports:
      - 38412:8080
    volumes:
      - /data/chat/db:/data
    networks:
      - chat

networks:
  chat:
    driver: bridge
